language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  - PACKAGE="logs-syslog" OCAML_VERSION=4.02
  - PACKAGE="logs-syslog" OCAML_VERSION=4.02 DEPOPTS="lwt x509 tls" TESTS=false
  - PACKAGE="logs-syslog" OCAML_VERSION=4.03 DEPOPTS="mirage-types lwt" TESTS=false
# once we have ipaddr working in 4.04  - PACKAGE="logs-syslog" OCAML_VERSION=4.04
notifications:
  email: false
